apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pv-claim 
  labels: 
    app: nextcloud
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
