apiVersion: v1
data:
  MYSQL_PASSWORD: cGFzc3cwcmQx
  MYSQL_ROOT_PASSWORD: cm9vdFBhc3N3MHJkMQ==
  MYSQL_USER: bmV4dGNsb3Vk
kind: Secret 
metadata:
  creationTimestamp: null
  name: nextcloud-db-secret
